### ISSUE TITLE
朋友你发个邮箱我给你提供智慧树和学习通的账号密码

### ISSUE THREAD

**Issue by XXXXBully** [Changbaiqi/yatori#10]

**Comment by Changbaiqi** [comment]
因为学业繁忙抽不出时间适配新平台，所以需要等25年后才有时间适配，同时也感谢您的支持。

**Comment by XXXXBully** [comment]
好的我也在研究接口，准备用易语言做，原本想看看楼主的方法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Changbaiqi/yatori] 朋友你发个邮箱我给你提供智慧树和学习通的账号密码 (Issue #10)




 
因为学业繁忙抽不出时间适配新平台，所以需要等25年后才有时间适配，同时也感谢您的支持。

**Comment by Changbaiqi** [comment]
嗯，不过目前项目最新版已经将学习通的登录接口给逆向了，可以直接登录。至于其他的课程获取啥的接口还没扒下来进行适配，不过只要过了登录其他的就容易些了，最怕的就是人机验证，普通图形验证码还好，最怕的是滑块验证码。

**Comment by XXXXBully** [comment]
是的，除了人脸我还没想好怎么解决，其他的话可以做打码，但是考试的滑块就难了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 下午2:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Changbaiqi/yatori] 朋友你发个邮箱我给你提供智慧树和学习通的账号密码 (Issue #10)




 
嗯，不过目前项目最新版已经将学习通的登录接口给逆向了，可以直接登录。至于其他的课程获取啥的接口还没扒下来进行适配，不过只要过了登录其他的就容易些了，最怕的就是人机验证，普通图形验证码还好，最怕的是滑块验证码。

**Comment by XXXXBully** [comment]
> 嗯，不过目前项目最新版已经将学习通的登录接口给逆向了，可以直接登录。至于其他的课程获取啥的接口还没扒下来进行适配，不过只要过了登录其他的就容易些了，最怕的就是人机验证，普通图形验证码还好，最怕的是滑块验证码。

哥们，顺便问一句你懂不懂微信小程序的登录怎么解决，微信id绑死了token让我头疼，目前能想到只能使用code授权，成本太高，请教一下如何解决

**Comment by Changbaiqi** [comment]
人脸的话可以通过用户自己拍照存起来，只要碰到人脸就直接上传用户照片就行，其实对于滑块，有种方法就是利用无头浏览器加上已有的参数+dddd库识别通过控制无头浏览器来完成滑块验证，不过这样的话效率并不算高而且额外多了个浏览器内核太重了。

**Comment by Changbaiqi** [comment]
> > 嗯，不过目前项目最新版已经将学习通的登录接口给逆向了，可以直接登录。至于其他的课程获取啥的接口还没扒下来进行适配，不过只要过了登录其他的就容易些了，最怕的就是人机验证，普通图形验证码还好，最怕的是滑块验证码。
> 
> 哥们，顺便问一句你懂不懂微信小程序的登录怎么解决，微信id绑死了token让我头疼，目前能想到只能使用code授权，成本太高，请教一下如何解决

这个我没研究过，暂时还不清楚。

**Comment by XXXXBully** [comment]
对的已经看到有个博主这么做出来了，占用太高，据我所知上传照片的这个接口好像变了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 下午3:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Changbaiqi/yatori] 朋友你发个邮箱我给你提供智慧树和学习通的账号密码 (Issue #10)




 
人脸的话可以通过用户自己拍照存起来，只要碰到人脸就直接上传用户照片就行，其实对于滑块，有种方法就是利用无头浏览器加上已有的参数+dddd库识别通过控制无头浏览器来完成滑块验证，不过这样的话效率并不算高而且额外多了个浏览器内核太重了。

**Comment by XXXXBully** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Changbaiqi/yatori] 朋友你发个邮箱我给你提供智慧树和学习通的账号密码 (Issue #10)




   
嗯，不过目前项目最新版已经将学习通的登录接口给逆向了，可以直接登录。至于其他的课程获取啥的接口还没扒下来进行适配，不过只要过了登录其他的就容易些了，最怕的就是人机验证，普通图形验证码还好，最怕的是滑块验证码。
  
哥们，顺便问一句你懂不懂微信小程序的登录怎么解决，微信id绑死了token让我头疼，目前能想到只能使用code授权，成本太高，请教一下如何解决
  
这个我没研究过，暂时还不清楚。
