### ISSUE TITLE
仓辉刷课无法使用

### ISSUE THREAD

**Issue by MaxuoAmos** [Changbaiqi/yatori#12]
仓辉刷课无法使用，显示如下面截图一样的画面不动，如果可以的话可以说下如何抓取log，下面也有我的Config设置的截图。

**Screenshots**
![屏幕截图 2024-05-16 164812](https://github.com/Changbaiqi/yatori/assets/122185836/759ca4b5-2499-406f-a66b-8e61635fa6bc)
![图片](https://github.com/Changbaiqi/yatori/assets/122185836/65f9ff57-2941-4775-b9db-3f7f0789a68a)

 - OS: [Win11]

**Comment by Changbaiqi** [comment]
> 仓辉刷课无法使用，显示如下面截图一样的画面不动，如果可以的话可以说下如何抓取log，下面也有我的Config设置的截图。
> 
> **Screenshots** ![屏幕截图 2024-05-16 164812](https://private-user-images.githubusercontent.com/122185836/331123480-759ca4b5-2499-406f-a66b-8e61635fa6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDk4MzcsIm5iZiI6MTcxNTg0OTUzNywicGF0aCI6Ii8xMjIxODU4MzYvMzMxMTIzNDgwLTc1OWNhNGI1LTI0OTktNDA2Zi1hNjZiLThlNjE2MzVmYTZiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODUyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWM2NDk5MDA4ZWEzY2RlMDE1ODZlN2E0NzE4MmMwNjY2YWNhNDM5OWM5ZTdjNWI5YjcyOTg5ODkyYTc5ZDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._AUqASD3NAc8B2hIjKwa7K6CaXQ6-LI2D25EsazzvOo) ![图片](https://private-user-images.githubusercontent.com/122185836/331123782-65f9ff57-2941-4775-b9db-3f7f0789a68a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDk4MzcsIm5iZiI6MTcxNTg0OTUzNywicGF0aCI6Ii8xMjIxODU4MzYvMzMxMTIzNzgyLTY1ZjlmZjU3LTI5NDEtNDc3NS1iOWRiLTNmN2YwNzg5YTY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwODUyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTQwZjNkMWNmY2E2NTA3MzExZTcyM2E0ZmQ5MDgyYTQ1OWFhYjRhOGQ3ZjYwMjU4OGMwY2ZmMjdmNzYyZGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UzEkTsu7NVYzotnpogbJ0hzkzzIWzdXt_XmSA3poFPk)
> 
> * OS: [Win11]
![image](https://github.com/Changbaiqi/yatori/assets/91747345/1823a2fb-49a4-48bd-9f2c-a27b2833d442)

**Comment by Changbaiqi** [comment]
日志我是直接输出的，没有区分debug日志（毕竟项目一开始单纯做着玩，没想那么多，后面没想到用的人越来越多了，项目也越来越大，现在就是一坨屎山）。

不过后续考虑重构重新设计架构了，要点时间。
