### ISSUE TITLE
他会自动显示课程已完成 学习公社的 

### ISSUE THREAD

**Issue by fenghuanglouchuan** [Changbaiqi/yatori#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Changbaiqi** [comment]
能否麻烦提供账号密码进行bug排查？(进群加Q私聊，群号932447008)

**Comment by Changbaiqi** [comment]
最新版本修复此BUG，[Yatori.v2.0.1-beta.4](https://github.com/Changbaiqi/yatori/releases/tag/v2.0.1-beta.4)
