### ISSUE TITLE
英华套壳的仓辉自动考试疑似无效

### ISSUE THREAD

**Issue by ghjcfrt** [Changbaiqi/yatori#17]
参数里写了自动考试，输出也输出了考试，但是并没有完成考试
![image](https://github.com/Changbaiqi/yatori/assets/73391769/95f033e3-15f1-4dbe-a80b-23e6014408ac)

**Comment by Changbaiqi** [comment]
> 因为考试今天截止，比较着急，所以可能无法在近期进行测试

建议切换go版本试试
